create table if not exists public.page_views (
  id bigint generated by default as identity primary key,
  path text not null,
  referrer text,
  user_agent text,
  created_at timestamptz not null default now()
);

alter table public.page_views enable row level security;

create index if not exists page_views_created_at_idx
  on public.page_views (created_at desc);

create index if not exists page_views_path_idx
  on public.page_views (path);

create table if not exists public.page_views_local (
  id bigint generated by default as identity primary key,
  path text not null,
  referrer text,
  user_agent text,
  created_at timestamptz not null default now()
);

alter table public.page_views_local enable row level security;

create index if not exists page_views_local_created_at_idx
  on public.page_views_local (created_at desc);

create index if not exists page_views_local_path_idx
  on public.page_views_local (path);
